$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
properties:
  hcat:name:
    type: string
    enum:
      - characteristics
      - crop_type
      - arable_crops
      - cereal
      - common_soft_wheat
      - winter_common_soft_wheat
      - spring_common_soft_wheat
      - unspecified_season_common_soft_wheat
      - durum_hard_wheat
      - winter_durum_hard_wheat
      - spring_durum_hard_wheat
      - unspecified_season_durum_hard_wheat
      - rye
      - winter_rye
      - spring_rye
      - unspecified_season_rye
      - barley
      - winter_barley
      - spring_barley
      - unspecified_season_barley
      - oats
      - winter_oats
      - spring_oats
      - unspecified_season_oats
      - grain_maize_corn_popcorn
      - unspecified_season_grain_maize_corn_popcorn
      - rice
      - unspecified_season_rice
      - triticale
      - winter_triticale
      - spring_triticale
      - unspecified_season_triticale
      - millet_sorghum
      - winter_millet_sorghum
      - spring_millet_sorghum
      - teff
      - unspecified_season_millet_sorghum
      - spelt
      - winter_spelt
      - spring_spelt
      - unspecified_season_spelt
      - meslin
      - winter_meslin
      - spring_meslin
      - unspecified_season_meslin
      - emmer
      - winter_emmer
      - spring_emmer
      - unspecified_season_emmer
      - einkorn
      - winter_einkorn
      - spring_einkorn
      - unspecified_season_einkorn
      - canary_seed_canaryseed
      - unspecified_season_canary_seed_canaryseed
      - unspecified_cereals
      - winter_unspecified_cereals
      - spring_unspecified_cereals
      - summer_unspecified_cereals
      - unspecified_season_unspecified_cereals
      - other_cereals
      - unspecified_season_other_cereals
      - legumes_dried_pulses_protein_crops
      - beans
      - chickpeas
      - esparsette_onobrychis
      - fenugreek
      - lentils
      - peas
      - sweet_lupins
      - unspecified_legumes_dried_pulses_protein_crops
      - other_dry_pulses
      - potatoes
      - sweet_potatoes
      - fodder_roots
      - industrial_nonfood_crops
      - tobacco
      - hops
      - cotton
      - rapeseed_rape
      - winter_rapeseed_rape
      - spring_rapeseed_rape
      - summer_rapeseed_rape
      - unspecified_season_rapeseed_rape
      - sunflower
      - poppy
      - winter_poppy
      - summer_poppy
      - flax_linseed
      - flax_linen
      - flax_linseed_oil
      - oilseed_crops
      - guizotia_abyssinica_nyger
      - hemp_cannabis
      - finola
      - fibre_crops
      - aromatic_medicinal_culinary_plants_spices_herbs
      - actaea_baneberry_christopher_herbs
      - alchemilla_ladys_mantle
      - anethum_dill
      - angelica
      - anise_aniseed
      - artemisia
      - basil
      - black_cumin
      - borage
      - calendula_marigold
      - caraway
      - catnip
      - chamomile
      - chervil
      - coriander
      - ericaceae_heather
      - galium_bedstraw
      - hibiscus
      - lavender_lavandula
      - lemon_balm_melissa
      - lovage_maggiplant
      - mints_peppermint
      - moldavian_dragonhead
      - nasturtiums
      - nettles
      - oregano
      - parsly
      - piper_pepper
      - polygonum
      - rosemary
      - rubia_tinctorum_common_madder
      - saffron_crocus_sativus
      - silver_comb
      - st_johns_wort
      - stachys_hedgenettle_chinese_artichoke
      - tarragon
      - thyme
      - valerian
      - yarrow
      - unspecified_aromatic_medicinal_culinary_plants_spices_herbs
      - other_aromatic_medicinal_culinary_plants_spices_herbs
      - marian_thistles
      - phacelia
      - camelina
      - onobrychis_sainfoins
      - other_industrial_crops
      - fresh_vegetables
      - flowers_ornamental_plants
      - adonis
      - anemones_windflowers
      - asters
      - begonias
      - bluebells
      - bulrush
      - burnet
      - carnation
      - chrysanthemum
      - cornflowers
      - corsican_hellebore
      - dahlia
      - daisy_daisies
      - dandelions
      - echinacea_sun_hat
      - edelweiss
      - fiddleneck_amsinckia
      - fuchsias
      - galega
      - gentians
      - gladiolus_gladioli
      - goldenrod
      - iris
      - isatis_tinctoria_woad
      - lilies
      - lotus
      - lunaria_honesty_silver
      - malva
      - milk_star
      - miscanthus_silvergrass
      - monstera_adansonii_eyelet
      - moonseed
      - narcissus_daffodil
      - peony_peonies
      - primrose
      - rhododendron
      - roses
      - rudbeckia_coneflowers
      - safflower
      - salsify
      - sanvitalia_procumbens
      - serradella
      - silene_catchfly
      - silphium_rosinweeds
      - snapdragons
      - stonecrop
      - tagetes
      - thimbles
      - tulips
      - viola
      - violets_pansies
      - zinnias
      - unspecified_flowers_ornamental_plants
      - other_flowers_ornamental_plants
      - plants_harvested_green
      - temporary_grass
      - poaceae_grasses
      - elymus
      - festuca_fescue
      - cocksfoot_catgrass
      - festulolium
      - lolium_ryegrass
      - setaria
      - sod_turf
      - switchgrass
      - timothy
      - legumes_harvested_green
      - alfalfa_lucerne
      - arachis
      - clover
      - melilot
      - vetches
      - unspecified_legumes_harvested_green
      - green_silo_maize
      - other_plants_harvested_green
      - arable_land_seed_seedlings
      - fallow_land_not_crop
      - kitchen_gardens
      - strawberries
      - cucurbits
      - cucumber_pickle
      - honeydew
      - melon
      - pumpkin_squash_gourd
      - watermelon
      - zucchini_courgette
      - pseudocereal
      - amaranth
      - buckwheat
      - quinoa
      - soy_soybeans
      - fennel
      - topinambur_jerusalem_artichoke
      - sage_chia
      - asparagus
      - brassicaceae_cruciferae
      - mustard
      - brassica_oleracea_cabbage
      - bok_choy_pak_choi
      - broccoli
      - brussels_sprouts
      - cauliflower
      - chinese_cabbage
      - collard_greens
      - gai_lan
      - kale
      - kohlrabi
      - red_cabbage
      - savoy_cabbage
      - white_cabbage
      - other_brassica_oleracea_cabbage
      - cress
      - horseradish
      - swede_rutabaga
      - alliums
      - chives
      - garlic
      - leek
      - onions
      - scallion
      - shallot
      - rhubarb
      - purslane
      - celery
      - celeriac
      - leaf_celery
      - aubergine_eggplant
      - artichoke
      - tomato
      - root_vegetables
      - arctium_burdock
      - beetroot_beets
      - carrots_daucus
      - mangelwurzel_fodder_beet
      - parsnips
      - radish
      - sugar_beet
      - turnips
      - unspecified_root_vegetables
      - capsicum
      - bell_pepper_paprika
      - chili_pepper
      - salads_lettuce_leaf_vegetables
      - chard
      - chicory_chicories
      - endive
      - iceberg
      - lambs_lettuce_rapunzel
      - rocket_arugula
      - sorrel
      - spinach
      - other_salads_lettuce_leaf_vegetables
      - other_arable_land_crops
      - pasture_meadow_grassland_grass
      - permanent_crops_perennial
      - orchards_fruits
      - amelanchier_serviceberry
      - apples
      - apricots
      - cherry_cherries
      - feijoa
      - fig
      - kiwi
      - medlar_loquat
      - nectarine
      - pawpaw
      - peach
      - pears
      - plums
      - pomegranate
      - quinces
      - unspecified_orchards_fruits
      - berries_berry_species
      - aronia_chokeberries
      - blackberry
      - blackcurrant_cassis
      - blueberry
      - cranberry
      - currants
      - gooseberry_gooseberries_cranberries
      - hippophae_sea_buckthorns_seaberry
      - jostaberry
      - raspberry_raspberries
      - redcurrant
      - rose_hip_rosehip
      - rowan_rowanberries
      - tayberry
      - unspecified_berries_berry_species
      - nuts
      - almond
      - hazelnuts_hazel
      - pecan
      - pistachio
      - sweet_chestnuts
      - walnuts
      - citrus_plantations
      - olive_plantations
      - olives_for_oil_production
      - table_olives
      - vineyards_wine_vine_rebland_grapes
      - nurseries_nursery
      - shrubberries_shrubs
      - azaleas
      - chaenomeles_cathayensis
      - crataegus_hawthorn
      - elder_elderberry
      - honeysuckle
      - ricinus_castor
      - wire_bush
      - ginko
      - avocado
      - legumes_from_trees
      - carob
      - mesquite
      - tamarind
      - unspecified_permanent_crops
      - other_permanent_crops_plantations
      - mushrooms_energy_genetically_modified_crops
      - energy_crops
      - genetically_modified_crops
      - igniscum_candy
      - sida_virginia_mallow
      - truffle
      - other_mushrooms_energy_crops_genetically_modified_crops
      - greenhouse_foil_film
      - tree_wood_forest
      - afforestation_reforestation
      - aspen
      - birch
      - dogwood_cornus
      - eucalyptus
      - oak
      - populus
      - willows_osiers
      - unspecified_tree_wood_forest
      - other_tree_wood_forest
      - peat_turf
      - unmaintained
      - not_known_and_other
  hcat:code:
    type: uint32
    enum:
      - 3000000000
      - 3300000000
      - 3301000000
      - 3301010000
      - 3301010100
      - 3301010101
      - 3301010102
      - 3301010199
      - 3301010200
      - 3301010201
      - 3301010202
      - 3301010299
      - 3301010300
      - 3301010301
      - 3301010302
      - 3301010399
      - 3301010400
      - 3301010401
      - 3301010402
      - 3301010499
      - 3301010500
      - 3301010501
      - 3301010502
      - 3301010599
      - 3301010600
      - 3301010699
      - 3301010700
      - 3301010799
      - 3301010800
      - 3301010801
      - 3301010802
      - 3301010899
      - 3301010900
      - 3301010901
      - 3301010902
      - 3301010904
      - 3301010999
      - 3301011000
      - 3301011001
      - 3301011002
      - 3301011099
      - 3301011100
      - 3301011101
      - 3301011102
      - 3301011199
      - 3301011200
      - 3301011201
      - 3301011202
      - 3301011299
      - 3301011300
      - 3301011301
      - 3301011302
      - 3301011399
      - 3301011400
      - 3301011499
      - 3301011500
      - 3301011501
      - 3301011502
      - 3301011503
      - 3301011599
      - 3301019900
      - 3301019999
      - 3301020000
      - 3301020100
      - 3301020200
      - 3301020300
      - 3301020400
      - 3301020500
      - 3301020600
      - 3301020700
      - 3301029800
      - 3301029900
      - 3301030000
      - 3301040000
      - 3301050000
      - 3301060000
      - 3301060100
      - 3301060200
      - 3301060300
      - 3301060400
      - 3301060401
      - 3301060402
      - 3301060403
      - 3301060499
      - 3301060500
      - 3301060600
      - 3301060601
      - 3301060602
      - 3301060700
      - 3301060701
      - 3301060702
      - 3301060800
      - 3301060900
      - 3301061000
      - 3301061001
      - 3301061100
      - 3301061200
      - 3301061201
      - 3301061202
      - 3301061203
      - 3301061204
      - 3301061205
      - 3301061206
      - 3301061207
      - 3301061208
      - 3301061209
      - 3301061210
      - 3301061211
      - 3301061212
      - 3301061213
      - 3301061214
      - 3301061215
      - 3301061216
      - 3301061217
      - 3301061218
      - 3301061219
      - 3301061220
      - 3301061221
      - 3301061222
      - 3301061223
      - 3301061224
      - 3301061225
      - 3301061226
      - 3301061227
      - 3301061228
      - 3301061229
      - 3301061230
      - 3301061231
      - 3301061232
      - 3301061233
      - 3301061234
      - 3301061235
      - 3301061236
      - 3301061237
      - 3301061238
      - 3301061239
      - 3301061298
      - 3301061299
      - 3301061300
      - 3301061400
      - 3301061500
      - 3301061600
      - 3301069900
      - 3301070000
      - 3301080000
      - 3301080100
      - 3301080200
      - 3301080300
      - 3301080400
      - 3301080500
      - 3301080600
      - 3301080700
      - 3301080800
      - 3301080900
      - 3301081000
      - 3301081100
      - 3301081200
      - 3301081300
      - 3301081400
      - 3301081500
      - 3301081600
      - 3301081700
      - 3301081800
      - 3301081900
      - 3301082000
      - 3301082100
      - 3301082200
      - 3301082300
      - 3301082400
      - 3301082500
      - 3301082600
      - 3301082700
      - 3301082800
      - 3301082900
      - 3301083000
      - 3301083100
      - 3301083200
      - 3301083300
      - 3301083400
      - 3301083500
      - 3301083600
      - 3301083700
      - 3301083800
      - 3301083900
      - 3301084000
      - 3301084100
      - 3301084200
      - 3301084300
      - 3301084400
      - 3301084500
      - 3301084600
      - 3301084700
      - 3301084800
      - 3301084900
      - 3301085000
      - 3301085100
      - 3301085200
      - 3301089800
      - 3301089900
      - 3301090000
      - 3301090100
      - 3301090200
      - 3301090201
      - 3301090202
      - 3301090203
      - 3301090204
      - 3301090205
      - 3301090206
      - 3301090207
      - 3301090208
      - 3301090209
      - 3301090300
      - 3301090301
      - 3301090302
      - 3301090303
      - 3301090304
      - 3301090305
      - 3301090398
      - 3301090400
      - 3301099900
      - 3301100000
      - 3301110000
      - 3301120000
      - 3301130000
      - 3301140000
      - 3301140100
      - 3301140200
      - 3301140300
      - 3301140400
      - 3301140500
      - 3301140600
      - 3301150000
      - 3301150100
      - 3301150200
      - 3301150300
      - 3301160000
      - 3301170000
      - 3301180000
      - 3301190000
      - 3301200000
      - 3301210000
      - 3301210100
      - 3301210200
      - 3301210201
      - 3301210202
      - 3301210203
      - 3301210204
      - 3301210205
      - 3301210206
      - 3301210207
      - 3301210208
      - 3301210209
      - 3301210210
      - 3301210211
      - 3301210212
      - 3301210299
      - 3301210300
      - 3301210400
      - 3301210500
      - 3301220000
      - 3301220100
      - 3301220200
      - 3301220300
      - 3301220400
      - 3301220500
      - 3301220600
      - 3301230000
      - 3301240000
      - 3301250000
      - 3301250100
      - 3301250200
      - 3301260000
      - 3301270000
      - 3301280000
      - 3301290000
      - 3301290100
      - 3301290200
      - 3301290300
      - 3301290400
      - 3301290500
      - 3301290600
      - 3301290700
      - 3301290800
      - 3301299800
      - 3301300000
      - 3301300100
      - 3301300200
      - 3301310000
      - 3301310100
      - 3301310200
      - 3301310300
      - 3301310400
      - 3301310500
      - 3301310600
      - 3301310700
      - 3301310800
      - 3301319900
      - 3301990000
      - 3302000000
      - 3303000000
      - 3303010000
      - 3303010100
      - 3303010200
      - 3303010300
      - 3303010400
      - 3303010500
      - 3303010600
      - 3303010700
      - 3303010800
      - 3303010900
      - 3303011000
      - 3303011100
      - 3303011200
      - 3303011300
      - 3303011400
      - 3303011500
      - 3303019800
      - 3303020000
      - 3303020100
      - 3303020200
      - 3303020300
      - 3303020400
      - 3303020500
      - 3303020600
      - 3303020700
      - 3303020800
      - 3303020900
      - 3303021000
      - 3303021100
      - 3303021200
      - 3303021300
      - 3303021400
      - 3303029800
      - 3303030000
      - 3303030100
      - 3303030200
      - 3303030300
      - 3303030400
      - 3303030500
      - 3303030600
      - 3303040000
      - 3303050000
      - 3303050100
      - 3303050200
      - 3303060000
      - 3303070000
      - 3303080000
      - 3303080100
      - 3303080200
      - 3303080300
      - 3303080400
      - 3303080500
      - 3303080600
      - 3303080700
      - 3303090000
      - 3303100000
      - 3303110000
      - 3303110100
      - 3303110200
      - 3303110300
      - 3303120000
      - 3303990000
      - 3304000000
      - 3304010000
      - 3304020000
      - 3304020100
      - 3304030000
      - 3304040000
      - 3304990000
      - 3305000000
      - 3306000000
      - 3306010000
      - 3306020000
      - 3306030000
      - 3306040000
      - 3306050000
      - 3306060000
      - 3306070000
      - 3306080000
      - 3306980000
      - 3306990000
      - 3307000000
      - 3308000000
      - 3399000000
  hcat:name_en:
    type: string
    minLength: 1