$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
required:
  - ec:hcat_name
  - ec:hcat_code
properties:
  ec:hcat_name:
    type: string
  ec:hcat_code:
    type: uint32
    minimum: 3000000000
    maximum: 3399000000
  ec:translated_name:
    type: string